name: BrainJ
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - aom=3.3.0=h0e60522_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blosc=1.21.0=h0e60522_0
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - bzip2=1.0.8=h8ffe710_4
  - c-blosc2=2.0.4=h09319c2_1
  - ca-certificates=2022.4.26=haa95532_0
  - cfitsio=4.1.0=h5a969a9_0
  - charls=2.3.4=h39d44d4_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - freetype=2.10.4=h546665d_1
  - giflib=5.2.1=h8d14728_2
  - imagecodecs=2022.2.22=py38hebefbeb_3
  - intel-openmp=2022.0.0=h57928b3_3663
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.1=py38haa95532_1
  - jpeg=9e=h8ffe710_0
  - jupyter_core=4.10.0=py38haa95532_0
  - jxrlib=1.1=h8ffe710_2
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libaec=1.0.6=h39d44d4_0
  - libavif=0.10.0=h8ffe710_1
  - libblas=3.9.0=14_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=14_win64_mkl
  - libcurl=7.82.0=h789b8ee_0
  - libdeflate=1.10=h8ffe710_0
  - liblapack=3.9.0=14_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libssh2=1.10.0=h680486a_2
  - libtiff=4.3.0=hc4061b1_3
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.2.11=h8ffe710_1014
  - libzopfli=1.0.3=h0e60522_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.5.1=py38h1f000d6_0
  - mkl=2022.0.0=h0e2418a_796
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nd2reader=3.3.0=pyhd8ed1ab_0
  - numpy=1.22.3=py38h5ed9b9d_2
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1o=h2bbff1b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pims=0.5=pyh9f0ad1d_1
  - pip=21.2.2=py38haa95532_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - python=3.8.12=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - setuptools=58.0.4=py38haa95532_0
  - slicerator=1.1.0=pyhd8ed1ab_0
  - snappy=1.1.8=ha925a31_3
  - sqlite=3.37.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.5.0=h2d74725_1
  - tk=8.6.12=h8ffe710_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - unicodedata2=14.0.0=py38h294d835_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py38haa95532_2
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.5=h62dcd97_1
  - zfp=0.5.5=h0e60522_8
  - zlib=1.2.11=h8ffe710_1014
  - zstd=1.5.2=h6255e5f_0
  - pip:
    - absl-py==1.1.0
    - aicsimageio==4.9.2
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - alabaster==0.7.12
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asciitree==0.3.3
    - astroid==2.12.12
    - astropy==5.1
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - atomicwrites==1.4.1
    - attrs==21.4.0
    - autopep8==1.6.0
    - babel==2.9.1
    - bcrypt==4.0.1
    - beautifulsoup4==4.10.0
    - bg-atlasapi==1.0.2
    - bg-space==0.6.0
    - binaryornot==0.4.4
    - black==22.10.0
    - bleach==4.1.0
    - boto3==1.21.37
    - botocore==1.24.37
    - brainrender==2.0.5.5
    - bs4==0.0.1
    - cachetools==4.2.4
    - cachey==0.2.1
    - certifi==2020.12.5
    - cffi==1.15.0
    - chardet==3.0.4
    - charset-normalizer==2.1.1
    - classification-models-3d==1.0.6
    - click==8.1.2
    - cloudpickle==1.3.0
    - colorama==0.4.6
    - colorcet==3.0.0
    - commonmark==0.9.1
    - cookiecutter==2.1.1
    - cryptography==38.0.3
    - csbdeep==0.7.2
    - dask==2022.4.0
    - dask-image==2022.9.0
    - defusedxml==0.7.1
    - denoiseg==0.3.0
    - deprecated==1.2.13
    - diff-match-patch==20200713
    - dill==0.3.3
    - dnspython==2.2.1
    - docstring-parser==0.13
    - docstring-to-markdown==0.10
    - docutils==0.17.1
    - efficientnet==1.0.0
    - efficientnet-3d==1.0.2
    - elasticdeform==0.4.9
    - elementpath==2.5.3
    - email-validator==1.3.0
    - fasteners==0.18
    - flake8==5.0.4
    - flatbuffers==23.1.4
    - fonttools==4.29.1
    - fpdf==1.7.2
    - freetype-py==2.2.0
    - frozenlist==1.3.3
    - fsspec==2022.3.0
    - future==0.18.2
    - gast==0.3.3
    - google==2.0.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - heapdict==1.0.1
    - hsluv==5.0.2
    - httplib2==0.17.4
    - idna==2.10
    - image-classifiers==1.0.0
    - imageio==2.16.2
    - imagesize==1.3.0
    - imgaug==0.2.9
    - importlib-metadata==5.0.0
    - importlib-resources==5.4.0
    - inflection==0.5.1
    - install==1.3.5
    - intervaltree==3.1.0
    - ipydatawidgets==4.3.2
    - ipykernel==6.17.1
    - ipython==8.1.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - isort==5.10.1
    - jaraco-classes==3.2.3
    - javabridge==1.0.16
    - jellyfish==0.9.0
    - jinja2==3.0.3
    - jinja2-time==0.2.0
    - jmespath==1.0.0
    - joblib==1.1.0
    - jsonschema==4.4.0
    - jupyter==1.0.0
    - jupyter-client==7.4.9
    - jupyter-console==6.4.3
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-core==4.9.2
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-http-over-ws==0.0.8
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - k3d==2.7.4
    - keras==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - keyring==23.11.0
    - kiwisolver==1.3.2
    - lazy-object-proxy==1.8.0
    - libclang==14.0.1
    - llvmlite==0.39.1
    - locket==0.2.1
    - loguru==0.6.0
    - lxml==4.8.0
    - magicgui==0.4.0
    - markdown==3.3.6
    - markupsafe==2.1.0
    - matplotlib-inline==0.1.3
    - mccabe==0.7.0
    - meshio==5.3.4
    - mistune==0.8.4
    - more-itertools==9.0.0
    - morphapi==0.1.7
    - morphio==3.3.3
    - msgpack==1.0.4
    - multidict==6.0.2
    - multiprocess==0.70.11.1
    - mypy-extensions==0.4.3
    - myterial==1.2.1
    - n2v==0.3.2
    - napari==0.4.15
    - napari-console==0.0.4
    - napari-plugin-engine==0.2.0
    - napari-svg==0.1.6
    - nbclient==0.5.12
    - nbconvert==6.4.2
    - nbformat==5.1.3
    - nd2==0.2.2
    - nest-asyncio==1.5.4
    - networkx==2.7.1
    - neurom==3.2.2
    - notebook==6.4.11
    - npe2==0.3.0
    - numba==0.56.3
    - numcodecs==0.10.2
    - numexpr==2.8.4
    - numpydoc==1.2.1
    - oauth2client==4.1.3
    - oauthlib==3.2.0
    - ome-types==0.3.1
    - opencv-python==4.5.5.62
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.4.1
    - pandocfilters==1.5.0
    - param==1.12.2
    - paramiko==2.12.0
    - partd==1.2.0
    - patchify==0.2.3
    - pathspec==0.10.2
    - pexpect==4.8.0
    - pillow==9.0.1
    - pims-nd2==1.1
    - pint==0.19.1
    - platformdirs==3.1.0
    - pluggy==1.0.0
    - pooch==1.3.0
    - prometheus-client==0.13.1
    - prompt-toolkit==3.0.28
    - protobuf==3.19.4
    - psutil==5.9.0
    - psygnal==0.3.3
    - ptyprocess==0.7.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.9.1
    - pycparser==2.21
    - pyct==0.4.8
    - pydantic==1.9.0
    - pydocstyle==6.2.3
    - pydot==1.3.0
    - pyerfa==2.0.0.1
    - pyflakes==2.5.0
    - pyinspect==0.1.0
    - pylint==2.15.5
    - pylint-venv==2.3.0
    - pyls-spyder==0.4.0
    - pynacl==1.5.0
    - pyopengl==3.1.6
    - pyparsing==3.0.7
    - pyqt5==5.15.7
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pyqtwebengine==5.15.6
    - pyqtwebengine-qt5==5.15.2
    - pyrsistent==0.18.1
    - python-bioformats==1.5.2
    - python-lsp-black==1.2.1
    - python-lsp-jsonrpc==1.0.0
    - python-lsp-server==1.7.1
    - python-slugify==6.1.2
    - pytomlpp==1.0.10
    - pytoolconfig==1.2.2
    - pytz==2021.3
    - pywavelets==1.2.0
    - pywin32==303
    - pywin32-ctypes==0.2.0
    - pywinpty==2.0.5
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qdarkstyle==3.0.3
    - qstylizer==0.2.2
    - qtawesome==1.2.1
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - requests-oauthlib==1.3.1
    - resource-backed-dask-array==0.1.0
    - retry==0.9.2
    - rich==12.6.0
    - rope==1.4.0
    - rsa==4.7.2
    - rtree==1.0.1
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - s3transfer==0.5.2
    - scikit-image==0.19.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - segmentation-models==1.0.1
    - segmentation-models-3d==1.0.4
    - send2trash==1.8.0
    - shapely==1.8.1.post1
    - six==1.15.0
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.3.1
    - sphinx==4.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - spyder==5.4.2
    - spyder-kernels==2.4.2
    - stardist==0.8.3
    - superqt==0.3.1
    - tables==3.7.0
    - tblib==1.7.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.10.0
    - tensorflow-gpu==2.10.1
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - terminado==0.13.3
    - testpath==0.6.0
    - text-unidecode==1.3
    - textdistance==4.5.0
    - three-merge==0.1.1
    - tifffile==2021.4.8
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.6
    - toolz==0.11.1
    - tornado==6.2
    - tqdm==4.64.0
    - traittypes==0.2.1
    - treelib==1.6.1
    - typer==0.4.1
    - typing-extensions==4.1.1
    - ujson==5.5.0
    - uritemplate==3.0.1
    - urllib3==1.25.11
    - vedo==2021.0.5
    - vispy==0.9.6
    - vtk==9.2.2
    - watchdog==2.1.9
    - webencodings==0.5.1
    - werkzeug==2.0.3
    - whatthepatch==1.0.3
    - widgetsnbextension==3.5.2
    - win32-setctime==1.1.0
    - wrapt==1.12.1
    - wslink==1.9.1
    - wurlitzer==3.0.2
    - xarray==2022.6.0
    - xmlschema==1.11.3
    - xmltodict==0.12.0
    - yapf==0.32.0
    - yarl==1.8.1
    - zarr==2.13.2
    - zipp==3.7.0
prefix: C:\Users\Luke_H\.conda\envs\BrainJ
