name: brainj
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - aom=3.3.0=h0e60522_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blosc=1.21.0=h0e60522_0
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - bzip2=1.0.8=h8ffe710_4
  - c-blosc2=2.0.4=h09319c2_1
  - ca-certificates=2022.4.26=haa95532_0
  - certifi=2022.12.7=py38haa95532_0
  - cfitsio=4.1.0=h5a969a9_0
  - charls=2.3.4=h39d44d4_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h546665d_1
  - giflib=5.2.1=h8d14728_2
  - imagecodecs=2022.2.22=py38hebefbeb_3
  - intel-openmp=2022.0.0=h57928b3_3663
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.1=py38haa95532_1
  - jinja2=3.1.2=py38haa95532_0
  - jpeg=9e=h8ffe710_0
  - jxrlib=1.1=h8ffe710_2
  - kiwisolver=1.4.4=py38hd77b12b_0
  - krb5=1.19.3=h1176d77_0
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libaec=1.0.6=h39d44d4_0
  - libavif=0.10.0=h8ffe710_1
  - libblas=3.9.0=14_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=14_win64_mkl
  - libcurl=7.82.0=h789b8ee_0
  - libdeflate=1.10=h8ffe710_0
  - liblapack=3.9.0=14_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libssh2=1.10.0=h680486a_2
  - libtiff=4.3.0=hc4061b1_3
  - libwebp=1.2.2=h57928b3_0
  - libwebp-base=1.2.2=h8ffe710_1
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.2.11=h8ffe710_1014
  - libzopfli=1.0.3=h0e60522_0
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.1=py38h2bbff1b_0
  - matplotlib-base=3.5.1=py38h1f000d6_0
  - mkl=2022.0.0=h0e2418a_796
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nd2reader=3.3.0=pyhd8ed1ab_0
  - numpy=1.22.3=py38h5ed9b9d_2
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1o=h2bbff1b_0
  - packaging=22.0=py38haa95532_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py38hdc2b20a_1
  - pims=0.5=pyh9f0ad1d_1
  - pip=21.2.2=py38haa95532_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38haa95532_0
  - python=3.8.12=h6244533_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pywin32=305=py38h2bbff1b_0
  - setuptools=58.0.4=py38haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - slicerator=1.1.0=pyhd8ed1ab_0
  - snappy=1.1.8=ha925a31_3
  - sqlite=3.37.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.5.0=h2d74725_1
  - tk=8.6.12=h8ffe710_0
  - unicodedata2=14.0.0=py38h294d835_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py38haa95532_2
  - xmltodict=0.12.0=pyhd3eb1b0_0
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.5=h62dcd97_1
  - zfp=0.5.5=h0e60522_8
  - zlib=1.2.11=h8ffe710_1014
  - zstd=1.5.2=h6255e5f_0
  - pip:
    - absl-py==1.4.0
    - aicsimageio==4.9.4
    - alabaster==0.7.13
    - arrow==1.2.3
    - asciitree==0.3.3
    - astroid==2.15.0
    - astunparse==1.6.3
    - atomicwrites==1.4.1
    - attrs==22.2.0
    - autopep8==1.6.0
    - babel==2.12.1
    - bcrypt==4.0.1
    - beautifulsoup4==4.11.2
    - binaryornot==0.4.4
    - black==23.1.0
    - bleach==6.0.0
    - cachetools==5.3.0
    - cffi==1.15.1
    - chardet==5.1.0
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - colorama==0.4.6
    - comm==0.1.2
    - cookiecutter==2.1.1
    - cryptography==39.0.2
    - csbdeep==0.7.3
    - dask==2023.3.0
    - debugpy==1.6.6
    - defusedxml==0.7.1
    - diff-match-patch==20200713
    - dill==0.3.6
    - dnspython==2.3.0
    - docstring-to-markdown==0.11
    - docutils==0.19
    - efficientnet==1.0.0
    - elementpath==4.0.1
    - email-validator==1.3.1
    - fasteners==0.18
    - fastjsonschema==2.16.3
    - flake8==6.0.0
    - flatbuffers==23.3.3
    - fsspec==2023.3.0
    - gast==0.4.0
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.51.3
    - h5py==3.8.0
    - idna==3.4
    - image-classifiers==1.0.0
    - imageio==2.26.0
    - imagesize==1.4.1
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - inflection==0.5.1
    - intervaltree==3.1.0
    - ipykernel==6.21.3
    - ipython==8.11.0
    - ipython-genutils==0.2.0
    - isort==5.12.0
    - jaraco-classes==3.2.3
    - jellyfish==0.9.0
    - jinja2-time==0.2.0
    - jsonschema==4.17.3
    - jupyter-client==7.4.9
    - jupyter-core==5.2.0
    - jupyterlab-pygments==0.2.2
    - keras==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - keyring==23.13.1
    - lazy-loader==0.1
    - lazy-object-proxy==1.9.0
    - libclang==15.0.6.1
    - llvmlite==0.39.1
    - locket==1.0.0
    - lxml==4.9.2
    - markdown==3.4.1
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mistune==2.0.5
    - more-itertools==9.1.0
    - mypy-extensions==1.0.0
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - networkx==3.0
    - numba==0.56.4
    - numcodecs==0.11.0
    - numpydoc==1.5.0
    - oauthlib==3.2.2
    - ome-types==0.3.3
    - opencv-python==4.7.0.72
    - opt-einsum==3.3.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - paramiko==3.0.0
    - partd==1.3.0
    - patchify==0.2.3
    - pathspec==0.11.0
    - pexpect==4.8.0
    - pint==0.20.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.1.1
    - pluggy==1.0.0
    - prompt-toolkit==3.0.38
    - protobuf==3.19.6
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.10.0
    - pycparser==2.21
    - pydantic==1.10.6
    - pydocstyle==6.2.3
    - pyflakes==3.0.1
    - pygments==2.14.0
    - pylint==2.17.0
    - pylint-venv==3.0.1
    - pyls-spyder==0.4.0
    - pynacl==1.5.0
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.1
    - pyqtwebengine==5.15.6
    - pyqtwebengine-qt5==5.15.2
    - pyrsistent==0.19.3
    - python-lsp-black==1.2.1
    - python-lsp-jsonrpc==1.0.0
    - python-lsp-server==1.7.1
    - python-slugify==8.0.1
    - pytoolconfig==1.2.5
    - pytz==2022.7.1
    - pywavelets==1.4.1
    - pywin32-ctypes==0.2.0
    - pyyaml==6.0
    - pyzmq==25.0.0
    - qdarkstyle==3.0.3
    - qstylizer==0.2.2
    - qtawesome==1.2.3
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - resource-backed-dask-array==0.1.0
    - rope==1.7.0
    - rsa==4.9
    - rtree==1.0.1
    - scikit-image==0.20.0
    - scipy==1.9.1
    - segmentation-models==1.0.1
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - soupsieve==2.4
    - sphinx==6.1.3
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - spyder==5.4.2
    - spyder-kernels==2.4.2
    - stardist==0.8.3
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.10.0
    - tensorflow-gpu==2.10.1
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.2.0
    - text-unidecode==1.3
    - textdistance==4.5.0
    - three-merge==0.1.1
    - tifffile==2023.2.28
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - tomlkit==0.11.6
    - toolz==0.12.0
    - tornado==6.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - typing-extensions==4.5.0
    - ujson==5.7.0
    - urllib3==1.26.14
    - watchdog==2.3.1
    - webencodings==0.5.1
    - werkzeug==2.2.3
    - whatthepatch==1.0.4
    - wrapt==1.15.0
    - xarray==2023.1.0
    - xmlschema==2.2.2
    - yapf==0.32.0
    - zarr==2.14.2
    - zipp==3.15.0
prefix: C:\Users\Alejandro\anaconda3\envs\brainj
